export const DETAILS = {
  EMPTY: "EMPTY",
  FORMAT: "FORMAT",
  TYPE: "TYPE",
  UNKNOWN: "UNKNOWN",
  UNIQUE: "UNIQUE",
  INVALID: "INVALID",
  SHORT: "SHORT",
  LONG: "LONG",
  MIN: "MIN",
  MAX: "MAX",
  LOCKED: "LOCKED",
  LIMIT: "LIMIT",
};

export default DETAILS;
