export const ERRORS_HTTP = {
  OK: 20,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNKNOWN_ERROR: 500,
};

export const ERRORS_TYPES = {
  EMPTY: "EMPTY",
  FORMAT: "FORMAT",
  TYPE: "TYPE",
  UNKNOWN: "UNKNOWN",
  UNIQUE: "UNIQUE",
  INVALID: "INVALID",
  SHORT: "SHORT",
  LONG: "LONG",
};
